name: Tests

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  test:
    name: Run tests
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test
        run: |
          echo "this is a fake test"

  merge:
    name: Merge Dependabot PRs
    runs-on: "ubuntu-latest"
    needs: test
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: "Approve the PR"
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.PAT }}

      # Don't auto-merge major version updates
      - name: "Auto-merge the PR"
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.PAT }}
